### ISSUE TITLE
crossExtensionState extension

### ISSUE THREAD

**Issue by BenjaminScholtens** [genesis-ai-dev/codex-scripture-viewer#2]
To enable extensions to interact, we will try to build a global state extension or `crossExtensionState` that is a dependency of any of our codex extensions:

- An extension can directly invoke the commands of another extension (see discussion [here](https://stackoverflow.com/a/50068416)), so we could call `crossExtensionState.getState` or `.setState` from another extension.
- If this fails to work as expected for some reason, we can fall back to updating a json file with project state

**Comment by ryderwishart** [comment]
See https://github.com/genesis-ai-dev/shared-state-store
